# ===================================================================================
# Project: ChatSkLearn
# File: src/services/embeddings/embedding_service.py
# Description: Embeds and stores chunks with embeddings for future use
# Author: LALAN KUMAR
# Created: [01-11-2025]
# Updated: [01-11-2025]
# LAST MODIFIED BY: LALAN KUMAR  [https://github.com/kumar8074]
# Version: 1.0.0
# ===================================================================================

import json
import os
import sys
import numpy as np
from pathlib import Path
from typing import List, Dict, Any
from langchain.embeddings import Embeddings

# Dynamically add the project root directory to sys.path
# Allows importing modules from the 'src' directory
current_file_path = os.path.abspath(__file__)
project_root = os.path.abspath(os.path.join(current_file_path, "../../../.."))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.logger import logging


def load_chunks(file_path: str | Path) -> List[Dict[str, Any]]:
    """
    Load JSONL (JSON Lines) data from the given file into a list of dictionaries.

    Args:
        file_path (str | Path): Path to the `.jsonl` file containing JSON objects.

    Returns:
        List[Dict[str, Any]]: A list of parsed JSON objects (each line corresponds to one dict).

    Raises:
        FileNotFoundError: If the file does not exist.
        json.JSONDecodeError: If a line in the file is not valid JSON.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    chunks = []
    with path.open("r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                chunks.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise json.JSONDecodeError(
                    f"Invalid JSON at line {line_number}: {e.msg}", e.doc, e.pos
                ) from e
            
    logging.info(f"Loaded {len(chunks)} chunks from {file_path}")
    return chunks


def generate_embeddings(
        chunks: List[Any], 
        batch_size: int = 100, 
        client: Embeddings | None = None
    ) -> List[List[float]]:
    """
    Generate embeddings for a list of texts using a LangChain-compatible embedding model.

    Args:
        chunks (List[Any]): A list of input chunks generated by scraper.
        batch_size (int, optional): Number of texts to process per batch. Defaults to 100.
        client (Embeddings | None, optional): A LangChain embedding model instance.

    Returns:
        List[List[float]]: A list of embedding vectors (one per input text).

    Raises:
        ValueError: If `client` is not provided.
    """
    if client is None:
        raise ValueError("An embedding client must be provided (e.g., GoogleGenerativeAIEmbeddings).")
    
    logging.info(f"Using Embedding model {client}")

    embeddings: List[List[float]] = []

    # Use enriched_text for embeddings (has context)
    texts = [chunk['enriched_text'] for chunk in chunks]

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        batch_embeddings: List[List[float]] = client.embed_documents(batch)
        embeddings.extend(batch_embeddings)
        logging.info(f"Processed {i + len(batch)}/{len(texts)} chunks")

    return embeddings


def combine_chunks_embeddings(
    chunks: List[Dict[str, Any]],
    embeddings: List[List[float]],
    output_file_path: str | Path
) -> None:
    """
    Combine a list of text chunks with their corresponding embeddings and save to disk as JSON.

    Args:
        chunks (List[Dict[str, Any]]): List of chunk dictionaries.
        embeddings (List[List[float]]): List of embedding vectors corresponding to the chunks.
        output_file_path (str | Path): File path where the combined JSON data will be saved.

    Returns:
        None

    Raises:
        ValueError: If the lengths of `chunks` and `embeddings` do not match.
        OSError: If there is an issue writing to the output file.
    """
    if len(chunks) != len(embeddings):
        raise ValueError(
            f"Number of chunks ({len(chunks)}) and embeddings ({len(embeddings)}) must be the same."
        )

    # Combine embeddings with chunks
    for chunk, embedding in zip(chunks, embeddings):
        chunk["embedding"] = embedding

    logging.info("Embeddings combined with all chunks")

    # Ensure parent directory exists
    output_path = Path(output_file_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save embedded chunks to JSON file
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(chunks, f, indent=2, ensure_ascii=False)

    logging.info(f"Chunks with embeddings saved to: {output_path}")
    
    
# Example usage:
#if __name__ == "__main__":
    #from src.config import EMBEDDING_MODEL
    #import time
    #start_time = time.time()
    #logging.info("Starting embedding generation process...")
    #logging.info("Loading chunks from file...")
    #chunks = load_chunks("temp/sklearn_scraped_data/chunks_for_rag.jsonl")
    #embeddings = generate_embeddings(chunks=chunks, batch_size=100, client=EMBEDDING_MODEL)
    #logging.info(f"Embeddings generated successfully")
    #logging.info("Combining chunks with embeddings and saving to file...")
    #combine_chunks_embeddings(chunks=chunks, embeddings=embeddings, output_file_path="temp/sklearn_scraped_data/chunks_with_embeddings.json")
    #duration = time.time() - start_time
    #logging.info(f"Embedding generation process completed in {duration:.2f} seconds.")